### ISSUE TITLE
Detected blocking call to open with args

### ISSUE THREAD

**Issue by r-jean-pierre** [petergridge/openweathermaphistory#39] opened 2024-06-29 13:11 UTC
Hi!

There are just warnings, but if it could be useful, I got many things like:

```
WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/home.pickle', 'wb') inside the event loop by custom integration 'openweathermaphistory' at custom_components/openweathermaphistory/weatherhistory.py, line 82: with open(file, 'wb') as myfile: (offender: /config/custom_components/openweathermaphistory/weatherhistory.py, line 82: with open(file, 'wb') as myfile:), please create a bug report at https://github.com/petergridge/openweathermaphistory/issues
```
and also for `owm_api_count.pickle`

Here is a stack of one of them:

```
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openweathermaphistory/sensor.py", line 110, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 323, in async_update
    self.store_data({ 'dailycalls':dailycalls},'owm_api_count')
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 82, in store_data
    with open(file, 'wb') as myfile:
```

**Comment by petergridge** [comment] 2024-07-01 08:04
Hi, This is a duplicate of Issue #35, it will be fixed in the next release, I have a couple of changes still to make for the next version but it should be out in the next few weeks.

**Comment by petergridge** [comment] 2024-08-11 06:12
V2.0.14 release, currently Beta for a few weeks for early adopters to verify. This fixes this issue.

**Closed** 2024-08-21 08:55 UTC
